enable-magisk-update = false

patches-source = "crimera/piko"
integrations-source = "crimera/revanced-integrations"
rv-brand = "Piko"

[x-material-design]
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
dpi = "120-640dpi"
arch = "arm64-v8a"
app-name = "X"
version = "formerly-twitter-11-22-0-release-0"
# patches-version = "latest"
riplib = true
# enabled = false
# included-patches = "'Hide Banner' 'Hide Live Threads' 'Disable chirp font' 'Hide Community Notes' 'Hide FAB' 'Hide FAB Menu Buttons' 'Custom sharing domain' 'Customize profile tabs' 'Hide promote button' 'Force enable translate' 'Add ability to copy media link' 'Customize Navigation Bar items' 'Hide promote button' 'Force enable translate' 'Delete from database'"

[x]
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
# included-patches = "'Hide Banner' 'Hide Live Threads' 'Disable chirp font' 'Hide Community Notes' 'Hide FAB' 'Hide FAB Menu Buttons' 'Custom sharing domain' 'Customize profile tabs' 'Hide promote button' 'Force enable translate' 'Add ability to copy media link' 'Customize Navigation Bar items' 'Hide promote button' 'Force enable translate' 'Delete from database'"
app-name = "X"
excluded-patches = "'Dynamic color'"
dpi = "120-640dpi"
arch = "arm64-v8a"
version = "formerly-twitter-11-22-0-release-0"
# patches-version = "latest"
riplib = true
